### ISSUE TITLE
noiseRepeat property / Depth property

### ISSUE THREAD

**Issue by Latentnaut** [keijiro/KvantTunnel#2]
Hi,

I've tried to make this 2 properties selection-able from Klak, without any success.

<img width="456" alt="screen shot 2017-03-09 at 14 36 59" src="https://cloud.githubusercontent.com/assets/22867200/23752617/581976d6-04d6-11e7-818a-b5d4ffa00c21.png">

Please, some light for this amazing tunnel :D

**Comment by keijiro** [comment]
This is not an issue with Tunnel but a limitation of Klak. These properties are not accessible from Klak because Klak doesn't have an accessor to integer properties.

I added an issue about this to Klak.

https://github.com/keijiro/Klak/issues/24

I'm closing this issue. Please check Klak#24 for further updates.
